apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: nw8lxczze-python
  janus-idp.io/tekton: nw8lxczze-python
  backstage.io/kubernetes-id: nw8lxczze-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: nw8lxczze-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
