apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: nw8lxczze-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: nw8lxczze-python 
  name: nw8lxczze-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: nw8lxczze-python 
